env:
  browser: true
  es2021: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:testing-library/react'
  - "plugin:jest-dom/recommended"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-debugger: "off"
  no-unused-vars: "off"

ignorePatterns: [
  "__tests__",
  "dist",
  "*.config.*"
]
