export const STATUS = {
  PENDING: "PENDING",
  DOWNLOADING: "DOWNLOADING",
  FAILED: "FAILED",
};

export const ERRORS = {
  INVALID_URL: 'INVALID_URL',
  URL_NOT_UNIQ: 'URL_NOT_UNIQ',
  INVALID_RSS: 'INVALID_RSS',
  ERR_NETWORK: 'ERR_NETWORK',
}

export const DELAY = 5000;
